listen=YES
listen_ipv6=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES

local_root=__FTP_ROOT__
user_sub_token=$USER

pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
pasv_addr_resolve=NO
pasv_address=__FTP_PASV_ADDRESS__

seccomp_sandbox=NO
pam_service_name=vsftpd

xferlog_enable=YES
log_ftp_protocol=YES
